name: Node.js

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '16.x'
        cache: 'npm'
    - run: npm ci
    - run: rm docs/index.html
    - run: npm run build
    - run: npm run dist
    - run: git config user.name scott
    - run: git config user.email scott.orlyck@gmail.com
    - run: git add .
    - run: git commit -m "Render and commit."
    - run: git push